name: Microservicio Usuarios CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  test_and_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: linting with ruff
      run: |
        ruff check . --exit-zero

    - name: Test with pytest
      run: |
        pytest -v

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        token: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/jhonenriquez98/ms-usuarios:latest
